project:
  type: website

format:
  html:
    theme: yeti
    css: styles.css
    highlight-style: pygments
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: '#a6caf0'
    collapse-below: lg
    search: true
    right:
      - icon: github
        href: https://github.com/BorjaRequena/Neural-Network-Course
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]
